plugins {
	id 'dev.architectury.loom'
}

dependencies {
	implementation project(':base')
	minecraft group: 'net.minecraft', name: 'minecraft', version: project.minecraft_version
	mappings loom.officialMojangMappings()
	modImplementation group: 'net.fabricmc', name: 'fabric-loader', version: project.loader_version

	modImplementation fileTree(include: ['*.jar'], dir: 'libs')
}

loom {
	mixin {
		defaultRefmapName = "${project.archives_base_name}-fabric-refmap.json"

		useLegacyMixinAp = true
	}
}

processResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}

java.withSourcesJar()
